version: '3'
services:
    jhipsterrestexample-app:
        image: jhipsterrestexample
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterrestexample-postgresql:5432/jHipsterRESTExample
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterrestexample-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsterrestexample-postgresql
